### ISSUE TITLE
为啥我的bili那个用不了，输入cookie后直接运行提示这样

### ISSUE THREAD

**Issue by nagashirosan** [kuekiko/scripts#1]
{'project_id': 72320, 'screen_id': 126698, 'sku_id': 380920}
{"errno":2,"errtag":0,"msg":"请先登录","data":false}

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\scripts-main\CP29\bili.py", line 185, in <module>
    create(token,buyer_info)
  File "C:\Users\Administrator\Desktop\scripts-main\CP29\bili.py", line 132, in create
    buyer_info_str = json.dumps([buyer_info[0]])
                                 ~~~~~~~~~~^^^
IndexError: list index out of range

进程已结束,退出代码1

**Comment by kuekiko** [comment]
需要自己提取cookie 填在脚本开头的COOKIE=""里面。 此脚本不建议用，长时间运行会触发B站的风控策略，建议开抢前再使用。
